name: instant_pay_app
description: PayRails B2B real-time payments app

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  flutter_secure_storage: ^9.2.4
  mobile_scanner: ^6.0.2
  qr_flutter: ^4.1.0
  nfc_manager: ^4.1.1
  uuid: ^4.5.1
  shared_preferences: ^2.3.0

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
